package bind

import (
	"path/filepath"
	"strings"
)

func ownedGeneratedFileName(bindingName string) string {
	return bindingName + "_gen.go"
}

func isOwnedBindingFile(bindingName, packageName, path, content string) bool {
	base := filepath.Base(path)
	if !strings.HasPrefix(base, bindingName) || !strings.HasSuffix(base, "_gen.go") {
		return false
	}

	return strings.Contains(content, "// Code generated by vxt bind. DO NOT EDIT.") &&
		strings.Contains(content, "// VXT binding: "+bindingName) &&
		strings.Contains(content, "// VXT package: "+packageName)
}
