package bind_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/vandordev/vxt/bind"
)

func TestWriteOutputCreatesDirectoryAndWritesGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir)
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if report.OutputDir != outDir {
		t.Fatalf("got output dir %q", report.OutputDir)
	}
	if len(report.FilesWritten) != 1 {
		t.Fatalf("got %d written files", len(report.FilesWritten))
	}
	if len(report.FilesOverwritten) != 0 {
		t.Fatalf("got %d overwritten files", len(report.FilesOverwritten))
	}

	target := filepath.Join(outDir, "service_gen.go")
	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	if string(content) != out.Files[0].Content {
		t.Fatalf("unexpected generated content:\n%s", string(content))
	}
}

func TestWriteOutputOverwritesExistingGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("mkdir output dir: %v", err)
	}

	target := filepath.Join(outDir, "service_gen.go")
	if err := os.WriteFile(target, []byte("old content"), 0o644); err != nil {
		t.Fatalf("seed existing file: %v", err)
	}

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir)
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if len(report.FilesWritten) != 0 {
		t.Fatalf("got %d written files", len(report.FilesWritten))
	}
	if len(report.FilesOverwritten) != 1 {
		t.Fatalf("got %d overwritten files", len(report.FilesOverwritten))
	}

	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read overwritten file: %v", err)
	}
	if string(content) != out.Files[0].Content {
		t.Fatalf("unexpected overwritten content:\n%s", string(content))
	}
}
