package bind_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/vandordev/vxt/bind"
)

func TestWriteOutputCreatesDirectoryAndWritesGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir)
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if report.OutputDir != outDir {
		t.Fatalf("got output dir %q", report.OutputDir)
	}
	if len(report.FilesWritten) != 1 {
		t.Fatalf("got %d written files", len(report.FilesWritten))
	}
	if len(report.FilesOverwritten) != 0 {
		t.Fatalf("got %d overwritten files", len(report.FilesOverwritten))
	}

	target := filepath.Join(outDir, "service_gen.go")
	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	if string(content) != out.Files[0].Content {
		t.Fatalf("unexpected generated content:\n%s", string(content))
	}
}

func TestWriteOutputOverwritesExistingGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("mkdir output dir: %v", err)
	}

	target := filepath.Join(outDir, "service_gen.go")
	if err := os.WriteFile(target, []byte("old content"), 0o644); err != nil {
		t.Fatalf("seed existing file: %v", err)
	}

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir)
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if len(report.FilesWritten) != 0 {
		t.Fatalf("got %d written files", len(report.FilesWritten))
	}
	if len(report.FilesOverwritten) != 1 {
		t.Fatalf("got %d overwritten files", len(report.FilesOverwritten))
	}

	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read overwritten file: %v", err)
	}
	if string(content) != out.Files[0].Content {
		t.Fatalf("unexpected overwritten content:\n%s", string(content))
	}
}

func TestWriteOutputScopedReconcileRemovesOnlyOwnedStaleFiles(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("mkdir output dir: %v", err)
	}

	currentPath := filepath.Join(outDir, "service_gen.go")
	staleOwnedPath := filepath.Join(outDir, "service_old_gen.go")
	otherBindingPath := filepath.Join(outDir, "repository_gen.go")
	notesPath := filepath.Join(outDir, "notes.txt")

	if err := os.WriteFile(currentPath, []byte("old service"), 0o644); err != nil {
		t.Fatalf("seed current file: %v", err)
	}
	if err := os.WriteFile(staleOwnedPath, []byte("// Code generated by vxt bind. DO NOT EDIT.\n// VXT binding: service\n// VXT package: servicevxt\npackage servicevxt\n"), 0o644); err != nil {
		t.Fatalf("seed stale owned file: %v", err)
	}
	if err := os.WriteFile(otherBindingPath, []byte("// Code generated by vxt bind. DO NOT EDIT.\n// VXT binding: repository\n// VXT package: repositoryvxt\npackage repositoryvxt\n"), 0o644); err != nil {
		t.Fatalf("seed other binding file: %v", err)
	}
	if err := os.WriteFile(notesPath, []byte("keep me"), 0o644); err != nil {
		t.Fatalf("seed notes file: %v", err)
	}

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir)
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if len(report.FilesRemoved) != 1 {
		t.Fatalf("got %d removed files", len(report.FilesRemoved))
	}
	if report.FilesRemoved[0] != staleOwnedPath {
		t.Fatalf("removed %q", report.FilesRemoved[0])
	}

	if _, err := os.Stat(currentPath); err != nil {
		t.Fatalf("expected current file to exist: %v", err)
	}
	if _, err := os.Stat(staleOwnedPath); !os.IsNotExist(err) {
		t.Fatalf("expected stale owned file removed, stat err=%v", err)
	}
	if _, err := os.Stat(otherBindingPath); err != nil {
		t.Fatalf("expected other binding file preserved: %v", err)
	}
	if _, err := os.Stat(notesPath); err != nil {
		t.Fatalf("expected notes file preserved: %v", err)
	}
}
