package bind_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/vandordev/vxt/bind"
)

func TestWriteOutputCreatesDirectoryAndWritesGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir, bind.WriteOptions{})
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if report.DryRun {
		t.Fatal("expected non-dry-run report")
	}
	if report.OutputDir != outDir {
		t.Fatalf("got output dir %q", report.OutputDir)
	}
	if len(report.FilesWritten) != 1 {
		t.Fatalf("got %d written files", len(report.FilesWritten))
	}
	if len(report.FilesOverwritten) != 0 {
		t.Fatalf("got %d overwritten files", len(report.FilesOverwritten))
	}
	if len(report.Actions) != 1 {
		t.Fatalf("got %d actions", len(report.Actions))
	}
	if report.Actions[0].Action != bind.WriteActionCreate {
		t.Fatalf("got action %#v", report.Actions[0])
	}

	target := filepath.Join(outDir, "service_gen.go")
	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	if string(content) != out.Files[0].Content {
		t.Fatalf("unexpected generated content:\n%s", string(content))
	}
}

func TestWriteOutputOverwritesExistingGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("mkdir output dir: %v", err)
	}

	target := filepath.Join(outDir, "service_gen.go")
	if err := os.WriteFile(target, []byte("old content"), 0o644); err != nil {
		t.Fatalf("seed existing file: %v", err)
	}

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir, bind.WriteOptions{})
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if report.DryRun {
		t.Fatal("expected non-dry-run report")
	}
	if len(report.FilesWritten) != 0 {
		t.Fatalf("got %d written files", len(report.FilesWritten))
	}
	if len(report.FilesOverwritten) != 1 {
		t.Fatalf("got %d overwritten files", len(report.FilesOverwritten))
	}
	if len(report.Actions) != 1 {
		t.Fatalf("got %d actions", len(report.Actions))
	}
	if report.Actions[0].Action != bind.WriteActionOverwrite {
		t.Fatalf("got action %#v", report.Actions[0])
	}

	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read overwritten file: %v", err)
	}
	if string(content) != out.Files[0].Content {
		t.Fatalf("unexpected overwritten content:\n%s", string(content))
	}
}

func TestWriteOutputScopedReconcileRemovesOnlyOwnedStaleFiles(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("mkdir output dir: %v", err)
	}

	currentPath := filepath.Join(outDir, "service_gen.go")
	staleOwnedPath := filepath.Join(outDir, "service_old_gen.go")
	otherBindingPath := filepath.Join(outDir, "repository_gen.go")
	notesPath := filepath.Join(outDir, "notes.txt")

	if err := os.WriteFile(currentPath, []byte("old service"), 0o644); err != nil {
		t.Fatalf("seed current file: %v", err)
	}
	if err := os.WriteFile(staleOwnedPath, []byte("// Code generated by vxt bind. DO NOT EDIT.\n// VXT binding: service\n// VXT package: servicevxt\npackage servicevxt\n"), 0o644); err != nil {
		t.Fatalf("seed stale owned file: %v", err)
	}
	if err := os.WriteFile(otherBindingPath, []byte("// Code generated by vxt bind. DO NOT EDIT.\n// VXT binding: repository\n// VXT package: repositoryvxt\npackage repositoryvxt\n"), 0o644); err != nil {
		t.Fatalf("seed other binding file: %v", err)
	}
	if err := os.WriteFile(notesPath, []byte("keep me"), 0o644); err != nil {
		t.Fatalf("seed notes file: %v", err)
	}

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir, bind.WriteOptions{})
	if err != nil {
		t.Fatalf("unexpected write error: %v", err)
	}
	if report.DryRun {
		t.Fatal("expected non-dry-run report")
	}
	if len(report.FilesRemoved) != 1 {
		t.Fatalf("got %d removed files", len(report.FilesRemoved))
	}
	if report.FilesRemoved[0] != staleOwnedPath {
		t.Fatalf("removed %q", report.FilesRemoved[0])
	}
	if len(report.Actions) != 2 {
		t.Fatalf("got %d actions", len(report.Actions))
	}

	if _, err := os.Stat(currentPath); err != nil {
		t.Fatalf("expected current file to exist: %v", err)
	}
	if _, err := os.Stat(staleOwnedPath); !os.IsNotExist(err) {
		t.Fatalf("expected stale owned file removed, stat err=%v", err)
	}
	if _, err := os.Stat(otherBindingPath); err != nil {
		t.Fatalf("expected other binding file preserved: %v", err)
	}
	if _, err := os.Stat(notesPath); err != nil {
		t.Fatalf("expected notes file preserved: %v", err)
	}
}

func TestWriteOutputDryRunCreateDoesNotTouchFilesystem(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir, bind.WriteOptions{DryRun: true})
	if err != nil {
		t.Fatalf("unexpected dry-run error: %v", err)
	}
	if !report.DryRun {
		t.Fatal("expected dry-run report")
	}
	if len(report.FilesWritten) != 1 || len(report.Actions) != 1 {
		t.Fatalf("unexpected dry-run report: %#v", report)
	}
	if _, err := os.Stat(outDir); !os.IsNotExist(err) {
		t.Fatalf("expected output dir to remain absent, stat err=%v", err)
	}
}

func TestWriteOutputDryRunOverwriteAndRemoveDoesNotMutateFilesystem(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, ".vxt")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("mkdir output dir: %v", err)
	}

	currentPath := filepath.Join(outDir, "service_gen.go")
	staleOwnedPath := filepath.Join(outDir, "service_old_gen.go")
	otherBindingPath := filepath.Join(outDir, "repository_gen.go")

	currentBefore := []byte("old current")
	staleBefore := []byte("// Code generated by vxt bind. DO NOT EDIT.\n// VXT binding: service\n// VXT package: servicevxt\npackage servicevxt\n")
	otherBefore := []byte("// Code generated by vxt bind. DO NOT EDIT.\n// VXT binding: repository\n// VXT package: repositoryvxt\npackage repositoryvxt\n")
	if err := os.WriteFile(currentPath, currentBefore, 0o644); err != nil {
		t.Fatalf("seed current file: %v", err)
	}
	if err := os.WriteFile(staleOwnedPath, staleBefore, 0o644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}
	if err := os.WriteFile(otherBindingPath, otherBefore, 0o644); err != nil {
		t.Fatalf("seed other file: %v", err)
	}

	out := bind.Output{
		BindingName: "service",
		PackageName: "servicevxt",
		Files: []bind.File{{
			Path: ".vxt/service_gen.go",
			Content: "// Code generated by vxt bind. DO NOT EDIT.\n" +
				"// VXT binding: service\n" +
				"// VXT package: servicevxt\n" +
				"package servicevxt\n",
		}},
	}

	report, err := bind.WriteOutput(out, outDir, bind.WriteOptions{DryRun: true})
	if err != nil {
		t.Fatalf("unexpected dry-run error: %v", err)
	}
	if !report.DryRun {
		t.Fatal("expected dry-run report")
	}
	if len(report.FilesOverwritten) != 1 || len(report.FilesRemoved) != 1 {
		t.Fatalf("unexpected dry-run report: %#v", report)
	}

	currentAfter, err := os.ReadFile(currentPath)
	if err != nil {
		t.Fatalf("read current file: %v", err)
	}
	if string(currentAfter) != string(currentBefore) {
		t.Fatalf("current file changed during dry-run")
	}
	if _, err := os.Stat(staleOwnedPath); err != nil {
		t.Fatalf("expected stale file to remain during dry-run: %v", err)
	}
	otherAfter, err := os.ReadFile(otherBindingPath)
	if err != nil {
		t.Fatalf("read other file: %v", err)
	}
	if string(otherAfter) != string(otherBefore) {
		t.Fatalf("other binding file changed during dry-run")
	}
}
